### ISSUE TITLE
Cannot view/create users for role

### ISSUE THREAD

**Issue by maartenvn** [directus/next#703] opened 2020-10-18 09:56 UTC
**Directus**: 9.0.0-rc.0
**MySQL**: Ver 14.14

User section appears empty when viewing a role and throws errors in the console:
![image](https://user-images.githubusercontent.com/6013068/96364102-fd460f80-1138-11eb-935b-b1e5d64a0790.png)

**Comment by maartenvn** [comment] 2020-10-18 10:14
I can confirm this is a MySQL bug, since it is working just fine on SQLite

**Comment by rijkvanzanten** [comment] 2020-10-19 18:58
I can't reproduce this issue on my end.. Could you check and confirm what records are saved in directus_relations?

The only thing I can think of rn is that either this relation is missing, or your users can't access it

![CleanShot 2020-10-19 at 14 57 38](https://user-images.githubusercontent.com/9141017/96499491-787ff200-121b-11eb-8c5e-3d737ae42b0d.png)

Is the user you're using an admin?

**Comment by rijkvanzanten** [comment] 2020-10-21 00:19
I think this was fixed in https://github.com/directus/next/commit/16cd8838a9fd2f94617f1818ba4060fb113146af

**Closed by rijkvanzanten** 2020-10-21 00:19 UTC
Labels: Needs More Info
