### ISSUE TITLE
Unable to delete project logo when linked

### ISSUE THREAD

**Issue by maartenvn** [directus/next#529] opened 2020-10-05 22:32 UTC
**Directus**: 9.0.0-beta.9 (Docker image)
**MySQL**: Ver 14.14

## Steps to reproduce

1. Go to Settings -> Project Settings
2. Upload an image for the project logo
3. Go to the file browser
4. Delete the image, linked to the logo

-> The file is not delete (nothing happens) but the image is wiped away. I am now unable to change the project logo to anything else and it appears to be broken:

![image](https://user-images.githubusercontent.com/6013068/95138751-4ecec180-076b-11eb-8800-c2f05e68b62e.png)
![image](https://user-images.githubusercontent.com/6013068/95138768-55f5cf80-076b-11eb-9617-e025eda01144.png)

### Terminal error
```
delete from `directus_files` where `id` in ('<uuid here>', '<uuid here>') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`production`.`directus_settings`, CONSTRAINT `directus_settings_project_logo_foreign` FOREIGN KEY (`project_logo`) REFERENCES `directus_files` (`id`)) 
Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`production`.`directus_settings`, CONSTRAINT `directus_settings_project_logo_foreign` FOREIGN KEY (`project_logo`) REFERENCES `directus_files` (`id`))
```

**Comment by benhaynes** [comment] 2020-10-06 13:39
Interesting. I see two solutions:

1. **Cascade Delete Relationships** — When deleting a file (or ideally any relational item), we also delete all relationships to that item. What's nice about this direction is that we can have an endpoint to get all related data, and then present to the user that _this action will delete 12 item references_.

2. **NULLify Corrupt Relationships** — Not sure if this will bypass the constraint, but I'm wondering if the App/API could handle these issues as they arise. If the related item is missing, it automatically NULLifies the field. This approach seems a bit riskier... since if you mess up your relationship, Directus might misunderstand what your existing data represents, and accidentally delete data it shouldn't.

@rijkvanzanten ?

**Comment by benhaynes** [comment] 2020-10-08 18:28
Duplicate of: https://github.com/directus/next/issues/594

**Closed by benhaynes** 2020-10-08 18:28 UTC
Labels: Bug, DB: MySQL, Docker
