### ISSUE TITLE
API returns error 500 on every request

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#657] opened 2020-10-14 21:27 UTC
Directus: v9.0.0-beta.10 (latest from git)
Node: 12
DB: SQLite

```
directus: TypeError: services_1.MetaService is not a constructor
directus:     at /Users/e01/Downloads/next/api/src/controllers/collections.ts:27:23
directus:     at Generator.next (<anonymous>)
directus:     at /Users/e01/Downloads/next/api/src/controllers/collections.ts:8:71
directus:     at new Promise (<anonymous>)
directus:     at __awaiter (/Users/e01/Downloads/next/api/src/controllers/collections.ts:4:12)
directus:     at /Users/e01/Downloads/next/api/src/controllers/collections.ts:25:40
directus:     at asyncUtilWrap (/Users/e01/Downloads/next/api/node_modules/express-async-handler/index.js:3:20)
directus:     at Layer.handle [as handle_request] (/Users/e01/Downloads/next/api/node_modules/express/lib/router/layer.js:95:5)
directus:     at next (/Users/e01/Downloads/next/api/node_modules/express/lib/router/route.js:137:13)
directus:     at Route.dispatch (/Users/e01/Downloads/next/api/node_modules/express/lib/router/route.js:112:3)
directus: 00:27:45 ✨ request errored GET 500 /collections 202ms
```

**Comment by rijkvanzanten** [comment] 2020-10-14 21:30
Duplicate of https://github.com/directus/next/issues/656

**Closed by rijkvanzanten** 2020-10-14 21:30 UTC
