### ISSUE TITLE
Error on database clean install

### ISSUE THREAD

**Issue by lluishi93** [directus/next#931] opened 2020-11-10 11:57 UTC
Version: 9 RC-8

Steps to reproduce: clean install using the following script:

```shell
install () {
    local email="admin@example.com"
    local password="1234"

    npx directus database install
    local role=$(npx directus roles create --name Administrator --admin)
    npx directus users create --email "${email}" --password "${password}" --role "${role}"

    echo "Email: ${email}"
    echo "Password: ${password}"
}

install
```

`sh db-install.sh`

![image](https://user-images.githubusercontent.com/14786440/98671069-fe431900-2353-11eb-9f53-05f13fdb84a7.png)

**Comment by rijkvanzanten** [comment] 2020-11-10 14:50
Duplicate of https://github.com/directus/next/issues/915

**Closed by rijkvanzanten** 2020-11-10 14:50 UTC
Labels: API, Bug, DB: MySQL
