### ISSUE TITLE
Translation is not deleted

### ISSUE THREAD

**Issue by Cruze** [directus/next#593] opened 2020-10-08 18:02 UTC
In v9 beta9 the translation is not automatically deleted when the main data record is deleted. 
The record remains in the database translation.
Directus V9 beta9
Ubuntu 18.04
Webmin 1.955
Virtualmin 6.12
Apache 2.4.29
MySQL version 5.7.31
NodeJS 14.13

**Comment by benhaynes** [comment] 2020-10-08 18:19
This seems related to other issues of stranded data. See https://github.com/directus/next/issues/529#issuecomment-704275805

@rijkvanzanten — I wonder if we should open a high-level "Relational Cascade Delete Option" ticket for all these.

**Comment by rijkvanzanten** [comment] 2020-10-08 18:20
Yeah that sounds like a good idea to me

**Comment by benhaynes** [comment] 2020-10-08 18:28
Duplicate of: https://github.com/directus/next/issues/594

**Closed by benhaynes** 2020-10-08 18:28 UTC
Labels: API, DB: MySQL
