### ISSUE TITLE
Confirmation for User's Two-Factor Authentication

### ISSUE THREAD

**Issue by benhaynes** [directus/next#403] opened 2020-09-22 18:50 UTC
Clicking on the "Two-Factor Authentication" within Users, opens an irreversible dialog... and then if you close out you will have it enabled with no way to turn it off. Then you will be locked out next time you have to log in.

We need to add a safety/confirmation for this somehow.

**Comment by rijkvanzanten** [comment] 2020-09-22 18:52
Duplicate of https://github.com/directus/next/issues/183

**Closed by rijkvanzanten** 2020-09-22 18:52 UTC
Labels: App, Tweak
