### ISSUE TITLE
RC 0: Unable to install - Failing when creating directus_files table

### ISSUE THREAD

**Issue by lluishi93** [directus/next#732] opened 2020-10-20 10:53 UTC
1. Create DIRECTUS project using npx or docker
2. Check that the following error occurs:

NPX:
![image](https://user-images.githubusercontent.com/14786440/96576552-a1af8980-12d2-11eb-83c7-f529707c5945.png)

Docker:
![image](https://user-images.githubusercontent.com/14786440/96576578-ac6a1e80-12d2-11eb-82e6-df7afc17fb19.png)

**Comment by benhaynes** [comment] 2020-10-20 13:06
Hmm, that's odd. I just went through the process and it worked seamlessly. Any more stack info? What versions are you using? Any specific database encoding/collation?

```
MySQL 5.7.26
Node v14.6.0
```

![Screen Shot 2020-10-20 at 8 48 58 AM](https://user-images.githubusercontent.com/522079/96589799-4326e300-12b3-11eb-9b0c-d5bc4da9f140.png)

**Comment by benhaynes** [comment] 2020-10-20 13:13
Oh wait, is this on Docker?

**Comment by lluishi93** [comment] 2020-10-20 13:14
Hi @benhaynes , it is the RC version, with MySQL 5.7. It is failing for me both in docker and local version.

**Comment by benhaynes** [comment] 2020-10-20 13:16
And your database encoding?

**Comment by lluishi93** [comment] 2020-10-20 13:22
Here it is:
![image](https://user-images.githubusercontent.com/14786440/96591810-f27dad00-12e7-11eb-8a3c-863c76f42d43.png)

Also, the only tables that get created when running the install are these:
![image](https://user-images.githubusercontent.com/14786440/96591851-ff9a9c00-12e7-11eb-83d6-cf88d236e54e.png)

**Comment by benhaynes** [comment] 2020-10-20 13:28
Maybe try setting the local database to `UTF8` just so we can rule that out? It seems like a MySQL version issue... perhaps @rijkvanzanten needs to explicitly set `allow_null`?

**Comment by rijkvanzanten** [comment] 2020-10-20 13:37
Duplicate of https://github.com/directus/next/issues/716#issuecomment-712521485

**Closed by rijkvanzanten** 2020-10-20 13:37 UTC
Labels: DB: MySQL, Docker, Needs More Info

**Comment by lluishi93** [comment] 2020-10-20 13:38
Ok, just saw this is a duplicate. JTLYK, just tried to set UTF8 without success:
![image](https://user-images.githubusercontent.com/14786440/96593125-75533780-12e9-11eb-8e5f-15e96894ba9a.png)
