### ISSUE TITLE
Can not set field as required

### ISSUE THREAD

**Issue by Fusseldieb** [directus/next#981] opened 2020-11-12 20:01 UTC
Using Postgres 13 and Directus v9.0.0-rc13 if I try to create a Decimal field and set it to "Require value", when creating I'm presented with following error:
![image](https://user-images.githubusercontent.com/4715129/98989936-8ff38780-2508-11eb-9b9b-610f551874e2.png)
Translation: 
> Column "size" from relation "table" contains NULL-values.

If I unselect "Require value" the field gets created just fine.

EDIT: Just tried it on my own fork locally and there it works fine (Windows 10 x64). On Ubuntu 16.04.7, however, it gives this error. Both are running version 13 of Postgres and v9.0.0-rc13. Now I am not sure if it's related to the database or the OS.

**Comment by rijkvanzanten** [comment] 2020-11-12 20:49
Duplicate of https://github.com/directus/next/issues/447

**Closed by rijkvanzanten** 2020-11-12 20:49 UTC
Labels: API, Bug, DB: Postgres

**Comment by Fusseldieb** [comment] 2020-11-12 20:53
@rijkvanzanten I saw this issue, but it's not a duplicate. #447 mentions SQLite.

Also, maybe this could eventually be useful: https://stackoverflow.com/a/42150852/3525780

**Comment by rijkvanzanten** [comment] 2020-11-12 21:07
@Fusseldieb It mentions SQLite, but the problem occurs in any vendor. If you have a column that contains values that are `NULL`, you can't set the column to `NOT NULL`

**Comment by Fusseldieb** [comment] 2020-11-12 21:30
> @Fusseldieb It mentions SQLite, but the problem occurs in any vendor. If you have a column that contains values that are `NULL`, you can't set the column to `NOT NULL`. The only real solution is for us to ask explicitly what you want your `null`s replaced with

Ahh, I had one of those braindead moments again. I didn't even saw there was a optional DEFAULT field. Maybe make it required when "Require" is activated?

**Comment by Fusseldieb** [comment] 2020-11-16 12:55
@rijkvanzanten Looking back into this, how can I make a field required in the frontend (not the schema), so it doesn't get submitted when empty?

**Comment by rijkvanzanten** [comment] 2020-11-16 14:38
By not having a default value? 

The problem you mentioned originally was only when you tried making a field required that already had `null` values in it. Creating a new `required` field without a default value is still possible

**Comment by Fusseldieb** [comment] 2020-11-16 14:45
> By not having a default value?
> 
> The problem you mentioned originally was only when you tried making a field required that already had `null` values in it. Creating a new `required` field without a default value is still possible

If I try to (String - Text input), it puts in "NULL" by default. The numeric won't even work without a default value. The idea is that the user fills the field out, and if he doesnt, it wouldn't get saved (in v8 it works fine).

**Comment by rijkvanzanten** [comment] 2020-11-16 14:46
That's the string "NULL" though, not actual `null`

**Comment by Fusseldieb** [comment] 2020-11-16 14:47
> That's the string "NULL" though, not actual `null`

But that's what it put there automatically. I didn't set any DEFAULT

**Comment by Fusseldieb** [comment] 2020-11-16 15:21
But this is still a problem:

![500ise](https://user-images.githubusercontent.com/4715129/99271914-f11ba380-2805-11eb-9fe9-3992f20f9ad3.gif)

I get it that the Require field is based on the database schema, but how would I do a "classical" required field, where no value is set and the user should type something in, else it doesn't get saved?

**Comment by Fusseldieb** [comment] 2020-11-16 15:30
Also, even if I give it a DEFAULT value, I get the 500 ISE error...
