### ISSUE TITLE
M2M can't show related data 

### ISSUE THREAD

**Issue by guilhermeaiolfi** [directus/next#406] opened 2020-09-23 04:13 UTC
Hi there,

Shouldn't this line: https://github.com/directus/next/blob/302763f7ca2019c226fd7021c461cd3cff7c5369/app/src/interfaces/many-to-many/many-to-many.vue#L16 be:

```vue
<template v-for="header in tableHeaders" v-slot:[`get(item,${header.value})`]="{ item }">{{header.value}}
```

It was the only way I've found to be able to use tag_id.label, for example, in a ```news_tags``` junction table where ```label``` relies on the ```tags``` table.

**Comment by rijkvanzanten** [comment] 2020-09-23 14:00
The slot is `item.<column>`, so lets say that the column name is "title", the slot would be accessed by `#item.title`. Therefore 

```
v-slot:[`item.${header.value}`]
```

equals

```
v-slot:[`item.title`]
```

equals

```
v-slot:item.title
```

equals

```
#item.title
```

so I believe that v-slot to be correct. That being said, there was another bug reported in the API that would case the response to be empty for certain relationally nested structures #350 / #376 which might very well be the cause of your troubles

**Comment by guilhermeaiolfi** [comment] 2020-09-23 14:29
Hmm, ok. But in a M2M we will have nested responses, because you need the data from the junction table and the related junction table. Taking the example @benhaynes is using to test, reciples can have ingredients. In this case, for this M2M relation we should be able to get the ```quantity``` from the ```reciple_ingredient``` table and the ```name``` from the ```ingredients``` table. The response from the server will be nested and to be able to show them in the table we'll need the lodash ```get``` to get those values. Unless the response is sent flatted from the API, them I would argue that it shouldn't.

**Comment by rijkvanzanten** [comment] 2020-09-23 14:32
The table uses `render-display`, 

https://github.com/directus/next/blob/302763f7ca2019c226fd7021c461cd3cff7c5369/app/src/interfaces/many-to-many/many-to-many.vue#L17-L27

Which—based on the configuration of the related field—in turn would render a `template` display (or any other), that then handles the displaying of the object

**Comment by rijkvanzanten** [comment] 2020-09-23 15:21
Ah, that could also cause that weirdness in the OP

**Comment by rijkvanzanten** [comment] 2020-09-23 22:07
@guilhermeaiolfi Turns out the problem was that the M2M interface passed the related collection to the render-display component as the current collection for the display instead of the junction table 🙂

**Comment by guilhermeaiolfi** [comment] 2020-09-23 22:56
Now I'm getting ```The relationship hasn't been configured correctly```. I tried removing the field and recreating, but I couldn't make it works. When I hover the field in the list field of that collection, it display "many-to-many", but when editing it says "Standard". I'll try to give you more information as I investigate it further.

**Comment by guilhermeaiolfi** [comment] 2020-09-23 23:28
It turns out  I had many entries for that relation in the DB. After removing all of them and recreating I am at a point where no errors appears in the console, but I am not getting what I wanted. Am I correct assuming that if the junction table has the field ```tag_id```, I could use ```tag_id.label``` in the interface field list? Because that's the only way the response from the API is bringing the data I wanted, like so:

```json
{"data":[{"tag_id":{"label":"Item One","id":2},"id":1}]}
```
So, the data is there, but ```Item One``` is not showing up in the table.  I think I have tried every combination possible. 

I am planning to taking some time to learn how everything correlates and works to be more helpful.

**Comment by rijkvanzanten** [comment] 2020-09-23 23:53
@guilhermeaiolfi That's correct! Just to confirm, are you running things from `main` latest commit, or through the npm release? I'm closing things on GH when they're fixed, but things may or may not have been released to NPM yet 🙂

**Comment by guilhermeaiolfi** [comment] 2020-09-24 00:22
@rijkvanzanten yes, I'm using ```main```, I am not relying in NPM. I pulled your lastest changes again, restarted everything and same problem. I'm definitely using the latest because I had to manually change the field ```last_login``` to ```last_access``` to be able to login again 😃   Just to be sure we are testing the same thing:

table news { id, title, text }
table news_tags { id, tag_id, news_id }
table tags { id, label }

Setting M2M in the news collection with the field name "tags", in the interface field list I just put ```tag_id.label```. In display I tried both: ```raw value``` and ```related values```.

**Comment by guilhermeaiolfi** [comment] 2020-09-30 01:43
So, since I am still not being able to do that, I thought I should give another try because since nobody seems to be having the same problem, it should be something in my end, right? So I dropped everything I had so far and start over. Dropped the old database, clone the repo for again in a new folder and did those steps:

1. initilize directus
> $ npx directus init
> >MySQl
> > 127.0.0.1
> > 3306
> > directus
> > directus
> > directus
> > admin@example.com
> > *******
> $ npx directus start

2. log in

3. create collection: "news" (id auto increment) with just two fields: 
   - ```title```: standard field (```string```) as interface: ```Text Input```  and display: ```Raw Value```
   - ```text```: standard field (```text```) as interface: ```WYSIWYG``` and display: ```Raw Value```

4. create collection: "tags" (id ```manually entered string```) with just one fields:
   - ```label```: standard field (```string```) as interface: ```Text Input``` and display: ```Raw value```

5. go back and create the m2m field in the news collection named: "tags"
   - configure the relation as:
```
        news      news_tags     tags
        id        news_id      
                  tag_id        id
```
   - select ```Many to Many``` Interface and add ```Tag ID``` -> ```Label``` as selected fields
   - select ```Raw Value```

The first issue is that when I am editing an entry for news, when clicking the "Create New", after submitting the form, besides the request returning 200 OK, the entry is not persisted in the DB. 

The second issues is the one described in the OP. If I go to the tags collection and create an entry there, when I return to the news entry I am trying to link to that tag, and selected the recently created tag I only get ```--``` in the label of that table.

**Comment by benhaynes** [comment] 2020-09-30 02:27
Thank you so much for this detailed and well formatted ticket! 💯 We'll take a look at this tomorrow...

**Comment by guilhermeaiolfi** [comment] 2020-10-01 00:59
I see the fix, thanks, the lodash ``get``` did the trick, I was wrong only where it should go.

Unfortunately, creating the entry for "Tags" using the "Create New" button when editing a registry of the News collection, still doesn't work. 

It is very weird, because when I try to debug it in Visual Code, it works. Without it (not in debug mode), it is not persisted to the DB. I guess some concurrency issue because of the async nature of the payload service. The news_tags entry is persisted, tho. But it is invalid, because it is related to something that doesn't exist. Then, if I try to create the same item again, it replicates that invalid relation.

**Comment by benhaynes** [comment] 2020-10-01 13:19
Not sure if we want this on a new ticket or not, but I'll reopen so this doesn't get lost.

**Comment by rijkvanzanten** [comment] 2020-10-01 13:46
Can you open a new issue detailing exactly what steps you take to reproduce this + versions @guilhermeaiolfi ? 🙂

**Closed by rijkvanzanten** 2020-10-01 13:46 UTC
Labels: App, Bug, Tweak

**Comment by guilhermeaiolfi** [comment] 2020-10-01 14:24
Sure
