### ISSUE TITLE
Docker initialisation missing creation of admin users on rc.12

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/next#953] opened 2020-11-11 17:42 UTC
**Steps to reproduce**

1. Create `docker-compuse.yml`

```
version: "3"

networks:
  backend:

services:
  backend-directus:
    image: directus/next:v9.0.0-rc.12
    env_file: .env
    ports:
      - "8055:8055"
    networks:
      - backend
```

2. Create `.env`

```
####################################################################################################
## Admin account

DIRECTUS_ADMIN_EMAIL="admin@local.com"
DIRECTUS_ADMIN_PASSWORD="pass"

####################################################################################################
## General

PORT=8055
PUBLIC_URL="/"

####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_PUBLIC_URL="/uploads"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="e891ab56-d5e2-4d92-b844-26098e62797b"
SECRET="E4OhqYHBFKZOv8tmFwiY7XODAsqM5Q7D"

ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

####################################################################################################
## SSO (OAuth) Providers

OAUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"
```

3. Run `docker-compose up`

The expected result is to create the admin account using `admin@local.com` and `pass`, however, Directus is installed without any problem but it does not appear to create the admin user.

4. Run `docker-compose down --rmi all -v` to clean any data created by any previous execution of the image

5. Change the directus image to `directus/next:v9.0.0-rc.3`

6. Run `docker-compose up` and the user is created successfully

Note: I also tested all the other images, the last one to be working apparently is `rc.3`

**Comment by juancarlosjr97** [comment] 2020-11-11 17:47
Additionally, as I am running test with other db, this one I am using the default which is `sqlite`

**Comment by rijkvanzanten** [comment] 2020-11-11 18:04
Wouldn't this be caused by that other issue https://github.com/directus/next/issues/948?

**Comment by rijkvanzanten** [comment] 2020-11-11 18:05
Duplicate of https://github.com/directus/next/issues/948

**Closed by rijkvanzanten** 2020-11-11 18:05 UTC
Labels: Duplicate

**Comment by juancarlosjr97** [comment] 2020-11-11 18:06
@rijkvanzanten could be, but in this case is not failing as far as I can see, just not creating the admin user, but could be...

**Comment by rijkvanzanten** [comment] 2020-11-11 18:12
The other issue failed on creating the role, and that logic is the same for creating users, so I'm 99% sure it's the same issue 🙂
