### ISSUE TITLE
Add "save with comment" 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#345] opened 2020-09-18 21:27 UTC
Allows you to explain the changes you made when saving the updates

**Comment by rijkvanzanten** [comment] 2020-09-18 21:27
And add a way to enforce this through permissions.

**Comment by benhaynes** [comment] 2020-10-07 18:55
Duplicate of https://github.com/directus/next/issues/9 and https://github.com/directus/next/issues/10

**Closed by benhaynes** 2020-10-07 18:55 UTC
Labels: API, App, New Feature
