### ISSUE TITLE
Cannot add required field with no default value (PostgreSQL 11)

### ISSUE THREAD

**Issue by jekuer** [directus/next#788] opened 2020-10-27 08:21 UTC
This is basically the same as with https://github.com/directus/next/issues/447.
However, I am not using SQLite, so the dirty quickfix there would not work.
Setup: V9.rc2, PostgreSQL 11.

Case: When I create a new field with type slug, set it as required, but do not enter a default value, the following error gets thrown:
🚨 error alter table "pages" add column "slug" varchar(255) not null - column "slug" contains null values
error: alter table "pages" add column "slug" varchar(255) not null - column "slug" contains null values
     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:278:15)
     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
     at Socket.emit (events.js:315:20)
     at addChunk (_stream_readable.js:309:12)
     at readableAddChunk (_stream_readable.js:284:9)
     at Socket.Readable.push (_stream_readable.js:223:10)
     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
✨ request errored POST 500 /fields/pages 39ms

I've tested a little bit and had the same thing with other input types. But from time to time, it then suddenly worked. Best way to reproduce is a clean setup with the slug type. Boolean/Toogle is also a good example.

_Should be also relevant for https://github.com/directus/next/issues/685, since there is no real UI feedback on the error. Depending on if it should be possible to add a required field without default (I think it should) or if it should not (then we would need proper feedback)._

**Comment by rijkvanzanten** [comment] 2020-10-27 09:53
I'll close this as a duplicate of #447 as it's the same cause

**Closed by rijkvanzanten** 2020-10-27 09:53 UTC
