### ISSUE TITLE
Building Directus

### ISSUE THREAD

**Issue by Fusseldieb** [directus/next#938] opened 2020-11-10 19:09 UTC
Hello,

I wanted to try the `next` build on my server and couldn't get it to combine api+app (Basically making "the suite"). 
Am I missing some crucial step? I already dig through the docs and couldn't find anything related.
It's not a simple `npm run build`, as it seems. This command just generates a `dist/` with some .js files, but it still isn't the final built version.

Or am I not supposed to build Directus on my own? :P

Thanks in advance!

**Comment by benhaynes** [comment] 2020-11-10 19:12
Duplicate of https://github.com/directus/next/issues/939

**Closed by benhaynes** 2020-11-10 19:12 UTC
Labels: Duplicate

**Comment by Fusseldieb** [comment] 2020-11-10 19:15
I created #938 and #939 by mistake as it seems, thanks for closing!

I submitted the Issue, GitHub presented me a 404 page, I got back and tried again. Oh well...
