### ISSUE TITLE
Cannot migrate MYSQL DB

### ISSUE THREAD

**Issue by Kinzi** [directus/next#988] opened 2020-11-13 07:00 UTC
When I run `npx directus database migrate:latest` with RC13 ( I get this roughly since RC8 though. SO DB wasn't migrated since then)

I get the following:

```
⠙ Running migrations...Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_fields_group_foreign'; check that column/key exists
    at Query.Sequence._packetToError (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Protocol._enqueue (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/seb/Code/cms/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/seb/Code/cms/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/seb/Code/cms/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/Users/seb/Code/cms/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/Users/seb/Code/cms/node_modules/knex/lib/runner.js:248:31)
    at /Users/seb/Code/cms/node_modules/knex/lib/runner.js:38:25
    at /Users/seb/Code/cms/node_modules/knex/lib/runner.js:277:24 {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlMessage: "Can't DROP 'directus_fields_group_foreign'; check that column/key exists",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `directus_fields` drop foreign key `directus_fields_group_foreign`'
}
```

**Comment by Kinzi** [comment] 2020-11-13 09:40
<img width="1024" alt="Bildschirmfoto 2020-11-13 um 11 39 58" src="https://user-images.githubusercontent.com/6689405/99057847-004fe680-25a5-11eb-8540-c2addbad091c.png">
This is what the table currently looks like. `directus_fields_group_foreign` exists as an index apperently....

**Comment by rijkvanzanten** [comment] 2020-11-13 14:53
@Kinzi I think this might've been caused by the fact that the migration ran, but failed due to that other issue we saw the other day. I think the `foreign` key constraint was removed successfully in that previous failed migration, which makes this migration fail because the key can't be found..

**Comment by Kinzi** [comment] 2020-11-13 16:11
@rijkvanzanten this could actually be right. I remember that I had to rerun something lately but can't pinpoint it.

I tried adding the foreign key manually to just get through the migration but failed in the attempt. I'm not a MYSQL coder at all...

**Comment by rijkvanzanten** [comment] 2020-11-13 16:27
Feel free to send over a dump on [Discord](https://discord.gg/directus). I can take a look for ya

**Comment by rijkvanzanten** [comment] 2020-11-13 16:28
I'll close this for now, as I'm fairly sure the previously failed migration left you in an "in-between" state

**Closed by rijkvanzanten** 2020-11-13 16:28 UTC
Labels: Invalid
