### ISSUE TITLE
[MSSQL] Can't connect to database

### ISSUE THREAD

**Issue by mscbpi** [directus/next#622] opened 2020-10-12 13:38 UTC
Docker image `v9.0.0-beta.10`
Trying to connect Azure MSSQL Instance

`💀 Can't connect to the database.`
`2 💀 The "config.options.port" property must be of type number.`

Looks like you have to cast the env value as int:

https://stackoverflow.com/questions/58699790/i-have-node-js-application-i-am-setting-env-using-dotenv-i-get-the-following-e
` port: parseInt(process.env.DB_PORT, 10)`

**Comment by rijkvanzanten** [comment] 2020-10-12 13:54
Duplicate of https://github.com/directus/next/issues/363

**Closed by rijkvanzanten** 2020-10-12 13:54 UTC
Labels: Bug, DB: SQL Server, Docker
