### ISSUE TITLE
Installation issue MySQL

### ISSUE THREAD

**Issue by Cruze** [directus/next#741] opened 2020-10-21 09:15 UTC
In version rc.1 I get an error message from MySQL during the installation routine

Something went wrong while seeding the database:

[ER_INVALID_DEFAULT] create table `directus_files` (`id` char(36) not null, `storage` varchar(255) not null, `filename_disk` varchar(255), `filename_download` varchar(255) not null, `title` varchar(255), `type` varchar(255), `folder` char(36), `uploaded_by` char(36), `uploaded_on` timestamp not null default CURRENT_TIMESTAMP, `modified_by` char(36), `modified_on` timestamp, `charset` varchar(50), `filesize` int unsigned not null default '0', `width` int unsigned, `height` int unsigned, `duration` int unsigned, `embed` varchar(200), `description` text, `location` text, `tags` text, `metadata` json) - ER_INVALID_DEFAULT: Invalid default value for 'modified_on'

Please try again

I tried it two times. Same problem.

MySQL Server:
MySQL version 5.7.31-0ubuntu0.18.04.1
NodeJS: 14.13

**Comment by rijkvanzanten** [comment] 2020-10-21 09:17
Duplicate of https://github.com/directus/next/issues/716

**Closed by rijkvanzanten** 2020-10-21 09:17 UTC
