### ISSUE TITLE
Unable to change scope of presets & bookmarks

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#641] opened 2020-10-14 05:01 UTC
Built a preset/bookmark for a table, went to the presets & bookmarks and changed the created entry to "Global", after saving it is still displaying my user as the scope.

**Comment by rijkvanzanten** [comment] 2020-10-14 13:36
Duplicate of https://github.com/directus/next/issues/536

**Closed by rijkvanzanten** 2020-10-14 13:36 UTC
