### ISSUE TITLE
Support and more info about SCIM

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#643] opened 2020-10-14 07:03 UTC
System for Cross-domain Identity Management

Would be great to get support and docs about SCIM in Directus v9.

In v8 we've got a bit of docs, but it's missing some examples and such - and support for v9.

My use case is handling all users identities in a separate Directus instance. Directus A would be having the users in Directus B.

**Comment by rijkvanzanten** [comment] 2020-10-14 13:30
Duplicate of https://github.com/directus/next/issues/17

**Closed by rijkvanzanten** 2020-10-14 13:30 UTC
