### ISSUE TITLE
Can't create entry for collection with translations

### ISSUE THREAD

**Issue by Naxos84** [directus/next#451] opened 2020-09-30 10:06 UTC
Hi and thankyou for that awesome product and the possibility to use this with NodeJs.

I created the project using `npx create-directus-project my-project`
I started the cms.
I create my first collection and want to add translations via "Create Field -> translations"
I added 3 fields to translations.
When I want to create an entry for that collection I get the following error:

```
11:58:27 ­ƒÜ¿  - SQLITE_MISUSE: not an error 
Error:  - SQLITE_MISUSE: not an error
11:58:27 Ô£¿ request errored POST 500 /items/articles 23ms
```

Directus Version 9.0.0-beta.3
OS Windows
Database SQLITE
ErrorMessage: as stated above

Screenshots:

![articles collection](https://user-images.githubusercontent.com/17813025/94672015-f20b7b00-0314-11eb-8bc7-97bef25cc95c.png)
![collections](https://user-images.githubusercontent.com/17813025/94672038-fe8fd380-0314-11eb-959a-9fdc6db6c330.png)
![automatically generated articles_translations](https://user-images.githubusercontent.com/17813025/94672088-0e0f1c80-0315-11eb-8bc0-7c082b3028bc.png)

**Comment by kukulaka** [comment] 2020-09-30 15:22
@Naxos84 I can not reproduce this error. I need a bit more information, does this error occur when you attempt to create a field within the translations screen?

**Comment by rijkvanzanten** [comment] 2020-09-30 15:25
@kukulaka This happens when you create an item with nested data:

```
{
  "title": "Example Parent",
  "author": {
    "name": "Nested author"
  }
}
```

This surfaces in translations as well, because that relies on nested relations too.

**Comment by Naxos84** [comment] 2020-09-30 17:32
The error occurs when I want to create an article.
Please check the last line of log error message.

If you still can't reproduce I'll check again tomorrow and try to explain in more detail what I did.

**Comment by rijkvanzanten** [comment] 2020-10-16 14:45
Same as https://github.com/directus/next/issues/598, fixed in https://github.com/directus/next/commit/2023566163146e24f0c2635e66f8bb0eef14964e

**Closed by rijkvanzanten** 2020-10-16 14:45 UTC
Labels: Bug, DB: SQLite
