### ISSUE TITLE
Allow_NULL + Required + Optional

### ISSUE THREAD

**Issue by benhaynes** [directus/next#373] opened 2020-09-21 15:58 UTC
We need to update this to be clearer... 

For O2M and M2M, this should be an INT for MIN (maybe MAX)

**Comment by rijkvanzanten** [comment] 2020-09-21 17:16
Allow null has been renamed to required for standard fields, the second is a duplicate of https://github.com/directus/next/issues/200

**Closed by rijkvanzanten** 2020-09-21 17:16 UTC
Labels: API, App
