### ISSUE TITLE
Migration on existing project fails

### ISSUE THREAD

**Issue by Clex1o1** [directus/next#941] opened 2020-11-10 20:15 UTC
`Error: ER_CANT_CREATE_TABLE: Can't create table `directus`.`directus_fields` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Protocol._enqueue (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/alexanderclassen/Projects/talentine-backend/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/runner.js:248:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/alexanderclassen/Projects/talentine-backend/node_modules/knex/lib/runner.js:277:18 {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlMessage: 'Can\'t create table `directus`.`directus_fields` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sqlState: 'HY000',
  index: 0,
  sql: 'alter table `directus_fields` add constraint `directus_fields_group_foreign` foreign key (`group`) references `directus_fields` (`id`) on update CASCADE on delete SET DEFAULT'
}`

update my existing project via `npm update` try to install my database again via `npm directus database install

**Comment by rijkvanzanten** [comment] 2020-11-10 20:30
Duplicate of https://github.com/directus/next/issues/915

**Closed by rijkvanzanten** 2020-11-10 20:30 UTC
