### ISSUE TITLE
npx create-directus-project / npx directus start fails on Windows using sqlite

### ISSUE THREAD

**Issue by MrPec** [directus/next#515] opened 2020-10-04 19:18 UTC
Tested on version v9.0.0-beta.8
When using default database suggestion (e.g. C:\source\data.db) for sqlite startup fails with error:

```
21:14:46 ­ƒÆÇ Can't connect to the database.
21:14:46 ÔÜá´©Å  pino.final with prettyPrint does not support flushing
21:14:46 ­ƒÆÇ SQLITE_CANTOPEN: unable to open database file
Error: SQLITE_CANTOPEN: unable to open database file
```

It works however when I specify a relative path ("./database.db").

**Comment by MrPec** [comment] 2020-10-04 19:22
It works when I specifiy the path using / instead of the suggested \

**Comment by rijkvanzanten** [comment] 2020-10-05 00:41
> It works when I specifiy the path using / instead of the suggested \


I'm assuming you mean the opposite? Using `\` instead of `/` ?

**Comment by MrPec** [comment] 2020-10-05 07:11
No, as I said. It works when I replace
DB_FILENAME="E:\Github\next\my-project\data.db"
with
DB_FILENAME="E:/Github/next/my-project/data.db"

**Comment by rijkvanzanten** [comment] 2020-10-12 21:44
Duplicate of #76

**Closed by rijkvanzanten** 2020-10-12 21:44 UTC
Labels: Bug, Package: create-directus-project
