### ISSUE TITLE
Cannot edit visibility of primary-key column

### ISSUE THREAD

**Issue by WoLfulus** [directus/next#637] opened 2020-10-14 04:45 UTC
When trying to display the ID in the details page (hidden by default), I'm unable to edit it because it tries to drop the column (fails because it's a primary key).

Not sure if it makes a difference, but ID column is an auto generated UUID

![image](https://user-images.githubusercontent.com/412397/95944553-d0070380-0dbe-11eb-80fc-b5d6bfa0aebe.png)

**Comment by apstanisic** [comment] 2020-10-14 07:50
Maybe duplicate of #613?

**Comment by rijkvanzanten** [comment] 2020-10-14 13:31
Duplicate of #613

**Closed by rijkvanzanten** 2020-10-14 13:31 UTC
